title: RDKit User Group Meeting 2020
description: >
  UGM JP 2020 is the 1st international user group meeting about RDKit in Japan. We are holding in June 2020. Please check the tickets on official WEB.
baseurl: "/UGMJP2020"
url: "https://rdkit-users-jp.github.io"

image: https://user-images.githubusercontent.com/7918702/75224128-41238780-57eb-11ea-8ab0-f90608790b0d.png
logo: http://rdkit-users.jp/UGMJP2020/css/2017_style/img/logos/rdkit-logo.png

include: ['_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
permalink: pretty
