title: UGM JP 2020
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "/UGMJP2020" # the subpath of your site, e.g. /blog
url: "https://rdkit-users-jp.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "{{ site.baseurl }}/css/_style/img/logos/rdkit-logo.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

# Build settings
markdown: kramdown
permalink: pretty
